openapi: 3.0.0
info:
  title: pokemon
  version: '2.0'
  description: pokeapiを参考に、サンプルコードに必要な情報だけopenapiにおこす
servers:
  - url: 'http://localhost:5000'
paths:
  '/api/v2/pokemon/{poke_id}':
    parameters:
      - schema:
          type: integer
        name: poke_id
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags:
        - pokemon
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pokemon'
              examples:
                図鑑番号1:
                  value:
                    id: 1
                    name: フシギダネ
                    sprites:
                      front_default: 'https://raw.githubuserco…er/sprites/pokemon/1.png'
                図鑑番号2:
                  value:
                    id: 2
                    name: フシギソウ
                    sprites:
                      front_default: 'https://raw.githubuserco…er/sprites/pokemon/2.png'
                図鑑番号3:
                  value:
                    id: 3
                    name: フシギバナ
                    sprites:
                      front_default: 'https://raw.githubuserco…er/sprites/pokemon/3.png'
        '404':
          description: Not Found
      operationId: get-api-v2-pokemon-poke_id
      description: ポケモンの情報をIDで取得する。
components:
  schemas:
    pokemon:
      title: pokemon
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        sprites:
          type: object
          properties:
            front_default:
              type: string
      x-examples:
        example-1:
          id: 1
          name: フシギダネ
          sprites:
            front_default: 'https://raw.githubuserco…er/sprites/pokemon/1.png'
        example-2:
          id: 2
          name: フシギソウ
          sprites:
            front_default: 'https://raw.githubuserco…er/sprites/pokemon/2.png'
        example-3:
          id: 3
          name: フシギバナ
          sprites:
            front_default: 'https://raw.githubuserco…er/sprites/pokemon/3.png'
      description: ''
tags:
  - name: pokemon
